//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Celeste.Mod.ConsistencyTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Celeste.Mod.ConsistencyTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function SplitVersionNumber(version){
        ///    var split = version.split(&quot;.&quot;);
        ///
        ///    return {
        ///        &quot;major&quot;: parseInt(split[0]),
        ///        &quot;minor&quot;: parseInt(split[1]),
        ///        &quot;patch&quot;: parseInt(split[2])
        ///    };
        ///}
        ///
        ///function areRoomsEqual(roomNew, roomOld) {
        ///    if(roomNew.debugRoomName != roomOld.debugRoomName){
        ///        return false;
        ///    }
        ///    if(roomNew.previousAttempts.length != roomOld.previousAttempts.length){
        ///        return false;
        ///    }
        ///    for(var i = 0; i &lt; roomNew.previousAttempts.length;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CCT_common_JS {
            get {
                return ResourceManager.GetString("CCT_common_JS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html {
        ///    width: 100%;
        ///    height: 100%;
        ///}
        ///
        ///body {
        ///    height: 100%;
        ///    width: 100%;
        ///    display: flex;
        ///    flex-direction: column;
        ///    justify-content: center;
        ///    align-items: center;
        ///    margin: 0;
        ///    color: white;
        ///    /* background-color: black; */
        ///}
        ///
        ///.hidden {
        ///    display: none;
        ///}
        ///
        ////* ===== TEXT STATS DISPLAY ===== */
        ///
        ///#stats-display {
        ///    width: 100%;
        ///    color: white;
        ///    font-weight: bold;
        ///    font-size: 2rem;
        ///    text-shadow: #000 0px 0px 2px,   #000 0px 0px 2px,   #0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CCTOverlay_CSS {
            get {
                return ResourceManager.GetString("CCTOverlay_CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Consistency Overlay&lt;/title&gt;
        ///	&lt;script src=&quot;common.js&quot;&gt;&lt;/script&gt;
        ///	&lt;script src=&quot;CCTOverlay.js&quot;&gt;&lt;/script&gt;
        ///	&lt;!-- Load stylesheet from &apos;PlainOverlay.css&apos; --&gt;
        ///	&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;CCTOverlay.css&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body id=&quot;body&quot;&gt;
        ///	&lt;div id=&quot;stats-display&quot;&gt;
        ///		&lt;div id=&quot;stats-left&quot;&gt;&lt;/div&gt;
        ///		&lt;div id=&quot;stats-center&quot;&gt;CCT - by viddie&lt;/div&gt;
        ///		&lt;div id=&quot;stats-right&quot;&gt;&lt;/div&gt;
        ///	&lt;/div&gt;
        ///	&lt;div id=&quot;room-attempts-container&quot;&gt;
        ///		&lt;div class=&quot;room-attempts-start-end&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CCTOverlay_HTML {
            get {
                return ResourceManager.GetString("CCTOverlay_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let settings = {};
        ///let defaultSettings = {
        ///    &quot;base&quot;: {
        ///        &quot;attempts&quot;: &quot;20&quot;,
        ///        &quot;refresh-time-ms&quot;: 1000,
        ///        &quot;text-format-left&quot;: &quot;Attempts: {chapter:goldenDeaths} ({chapter:goldenDeathsSession}) [{room:goldenDeaths}]&lt;br&gt;Choke Rate: {room:chokeRate}&lt;br&gt;PB: {pb:best} (Session: {pb:bestSession})&quot;,
        ///        &quot;text-format-center&quot;: &quot;{room:name}: {room:successRate} ({room:successes}/{room:attempts})&lt;br&gt;CP: {checkpoint:successRate}&lt;br&gt;Total: {chapter:successRate}&quot;,
        ///        &quot;text-format-right&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CCTOverlay_JS {
            get {
                return ResourceManager.GetString("CCTOverlay_JS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Forsaken City&quot;,&quot;chapterSID&quot;:&quot;Celeste/1-ForsakenCity&quot;,&quot;sideName&quot;:&quot;B-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:5,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;00&quot;},{&quot;debugRoomName&quot;:&quot;01&quot;},{&quot;debugRoomName&quot;:&quot;02&quot;},{&quot;debugRoomName&quot;:&quot;02b&quot;},{&quot;debugRoomName&quot;:&quot;03&quot;}]},{&quot;name&quot;:&quot;Contraption&quot;,&quot;abbreviation&quot;:&quot;CT&quot;,&quot;roomCount&quot;:5,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;04&quot;},{&quot;debugRoomName&quot;:&quot;05&quot;},{&quot;debugRoomName&quot;:&quot;05b&quot;},{&quot;debugRoomName&quot;:&quot;06&quot;},{&quot;debugRoomName&quot;:&quot;07&quot;}]},{&quot;name&quot;:&quot;Scrap Pit&quot;,&quot;ab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celeste_1_ForsakenCity_BSide {
            get {
                return ResourceManager.GetString("Celeste_1_ForsakenCity_BSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Forsaken City&quot;,&quot;chapterSID&quot;:&quot;Celeste/1-ForsakenCity&quot;,&quot;sideName&quot;:&quot;C-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:3,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;00&quot;},{&quot;debugRoomName&quot;:&quot;01&quot;},{&quot;debugRoomName&quot;:&quot;02&quot;}]}],&quot;roomCount&quot;:3}.
        /// </summary>
        internal static string Celeste_1_ForsakenCity_CSide {
            get {
                return ResourceManager.GetString("Celeste_1_ForsakenCity_CSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Forsaken City&quot;,&quot;chapterSID&quot;:&quot;Celeste/1-ForsakenCity&quot;,&quot;sideName&quot;:&quot;A-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:6,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;1&quot;},{&quot;debugRoomName&quot;:&quot;2&quot;},{&quot;debugRoomName&quot;:&quot;3&quot;},{&quot;debugRoomName&quot;:&quot;4&quot;},{&quot;debugRoomName&quot;:&quot;3b&quot;},{&quot;debugRoomName&quot;:&quot;5&quot;}]},{&quot;name&quot;:&quot;Crossing&quot;,&quot;abbreviation&quot;:&quot;CR&quot;,&quot;roomCount&quot;:8,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;6&quot;},{&quot;debugRoomName&quot;:&quot;6a&quot;},{&quot;debugRoomName&quot;:&quot;6b&quot;},{&quot;debugRoomName&quot;:&quot;6c&quot;},{&quot;debugRoomName&quot;:&quot;7&quot;},{&quot;debugRoomNam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celeste_1_ForsakenCity_Normal {
            get {
                return ResourceManager.GetString("Celeste_1_ForsakenCity_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Old Site&quot;,&quot;chapterSID&quot;:&quot;Celeste/2-OldSite&quot;,&quot;sideName&quot;:&quot;B-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:6,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;start&quot;},{&quot;debugRoomName&quot;:&quot;00&quot;},{&quot;debugRoomName&quot;:&quot;01&quot;},{&quot;debugRoomName&quot;:&quot;01b&quot;},{&quot;debugRoomName&quot;:&quot;02b&quot;},{&quot;debugRoomName&quot;:&quot;02&quot;}]},{&quot;name&quot;:&quot;Combination Lock&quot;,&quot;abbreviation&quot;:&quot;CL&quot;,&quot;roomCount&quot;:5,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;03&quot;},{&quot;debugRoomName&quot;:&quot;04&quot;},{&quot;debugRoomName&quot;:&quot;05&quot;},{&quot;debugRoomName&quot;:&quot;06&quot;},{&quot;debugRoomName&quot;:&quot;07&quot;}]},{&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celeste_2_OldSite_BSide {
            get {
                return ResourceManager.GetString("Celeste_2_OldSite_BSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Old Site&quot;,&quot;chapterSID&quot;:&quot;Celeste/2-OldSite&quot;,&quot;sideName&quot;:&quot;C-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:3,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;00&quot;},{&quot;debugRoomName&quot;:&quot;01&quot;},{&quot;debugRoomName&quot;:&quot;02&quot;}]}],&quot;roomCount&quot;:3}.
        /// </summary>
        internal static string Celeste_2_OldSite_CSide {
            get {
                return ResourceManager.GetString("Celeste_2_OldSite_CSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Old Site&quot;,&quot;chapterSID&quot;:&quot;Celeste/2-OldSite&quot;,&quot;sideName&quot;:&quot;A-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:9,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;start&quot;},{&quot;debugRoomName&quot;:&quot;0&quot;},{&quot;debugRoomName&quot;:&quot;1&quot;},{&quot;debugRoomName&quot;:&quot;d0&quot;},{&quot;debugRoomName&quot;:&quot;d7&quot;},{&quot;debugRoomName&quot;:&quot;d8&quot;},{&quot;debugRoomName&quot;:&quot;d3&quot;},{&quot;debugRoomName&quot;:&quot;d2&quot;},{&quot;debugRoomName&quot;:&quot;3x&quot;}]},{&quot;name&quot;:&quot;CP2&quot;,&quot;abbreviation&quot;:&quot;CP2&quot;,&quot;roomCount&quot;:15,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;3&quot;},{&quot;debugRoomName&quot;:&quot;4&quot;},{&quot;debugRoomName&quot;:&quot;5&quot;} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celeste_2_OldSite_Normal {
            get {
                return ResourceManager.GetString("Celeste_2_OldSite_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Celestial Resort&quot;,&quot;chapterSID&quot;:&quot;Celeste/3-CelestialResort&quot;,&quot;sideName&quot;:&quot;B-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:6,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;00&quot;},{&quot;debugRoomName&quot;:&quot;01&quot;},{&quot;debugRoomName&quot;:&quot;02&quot;},{&quot;debugRoomName&quot;:&quot;03&quot;},{&quot;debugRoomName&quot;:&quot;04&quot;},{&quot;debugRoomName&quot;:&quot;05&quot;}]},{&quot;name&quot;:&quot;Staff Quarters&quot;,&quot;abbreviation&quot;:&quot;SQ&quot;,&quot;roomCount&quot;:5,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;06&quot;},{&quot;debugRoomName&quot;:&quot;07&quot;},{&quot;debugRoomName&quot;:&quot;08&quot;},{&quot;debugRoomName&quot;:&quot;09&quot;},{&quot;debugRoomName&quot;:&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celeste_3_CelestialResort_BSide {
            get {
                return ResourceManager.GetString("Celeste_3_CelestialResort_BSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Celestial Resort&quot;,&quot;chapterSID&quot;:&quot;Celeste/3-CelestialResort&quot;,&quot;sideName&quot;:&quot;C-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:3,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;00&quot;},{&quot;debugRoomName&quot;:&quot;01&quot;},{&quot;debugRoomName&quot;:&quot;02&quot;}]}],&quot;roomCount&quot;:3}.
        /// </summary>
        internal static string Celeste_3_CelestialResort_CSide {
            get {
                return ResourceManager.GetString("Celeste_3_CelestialResort_CSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Celestial Resort&quot;,&quot;chapterSID&quot;:&quot;Celeste/3-CelestialResort&quot;,&quot;sideName&quot;:&quot;A-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:17,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;s0&quot;},{&quot;debugRoomName&quot;:&quot;s1&quot;},{&quot;debugRoomName&quot;:&quot;s2&quot;},{&quot;debugRoomName&quot;:&quot;s3&quot;},{&quot;debugRoomName&quot;:&quot;0x-a&quot;},{&quot;debugRoomName&quot;:&quot;00-a&quot;},{&quot;debugRoomName&quot;:&quot;02-a&quot;},{&quot;debugRoomName&quot;:&quot;02-b&quot;},{&quot;debugRoomName&quot;:&quot;03-a&quot;},{&quot;debugRoomName&quot;:&quot;05-a&quot;},{&quot;debugRoomName&quot;:&quot;06-a&quot;},{&quot;debugRoomName&quot;:&quot;07-a&quot;},{&quot;debugRoomName&quot;:&quot;07-b&quot;}, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celeste_3_CelestialResort_Normal {
            get {
                return ResourceManager.GetString("Celeste_3_CelestialResort_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Golden Ridge&quot;,&quot;chapterSID&quot;:&quot;Celeste/4-GoldenRidge&quot;,&quot;sideName&quot;:&quot;B-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:5,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;a-00&quot;},{&quot;debugRoomName&quot;:&quot;a-01&quot;},{&quot;debugRoomName&quot;:&quot;a-02&quot;},{&quot;debugRoomName&quot;:&quot;a-03&quot;},{&quot;debugRoomName&quot;:&quot;a-04&quot;}]},{&quot;name&quot;:&quot;Stepping Stones&quot;,&quot;abbreviation&quot;:&quot;SS&quot;,&quot;roomCount&quot;:5,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;b-00&quot;},{&quot;debugRoomName&quot;:&quot;b-01&quot;},{&quot;debugRoomName&quot;:&quot;b-02&quot;},{&quot;debugRoomName&quot;:&quot;b-03&quot;},{&quot;debugRoomName&quot;:&quot;b-04&quot;}]},{&quot;n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celeste_4_GoldenRidge_BSide {
            get {
                return ResourceManager.GetString("Celeste_4_GoldenRidge_BSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Golden Ridge&quot;,&quot;chapterSID&quot;:&quot;Celeste/4-GoldenRidge&quot;,&quot;sideName&quot;:&quot;C-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:3,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;00&quot;},{&quot;debugRoomName&quot;:&quot;01&quot;},{&quot;debugRoomName&quot;:&quot;02&quot;}]}],&quot;roomCount&quot;:3}.
        /// </summary>
        internal static string Celeste_4_GoldenRidge_CSide {
            get {
                return ResourceManager.GetString("Celeste_4_GoldenRidge_CSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Golden Ridge&quot;,&quot;chapterSID&quot;:&quot;Celeste/4-GoldenRidge&quot;,&quot;sideName&quot;:&quot;A-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:11,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;a-00&quot;},{&quot;debugRoomName&quot;:&quot;a-01&quot;},{&quot;debugRoomName&quot;:&quot;a-01x&quot;},{&quot;debugRoomName&quot;:&quot;a-02&quot;},{&quot;debugRoomName&quot;:&quot;a-03&quot;},{&quot;debugRoomName&quot;:&quot;a-04&quot;},{&quot;debugRoomName&quot;:&quot;a-05&quot;},{&quot;debugRoomName&quot;:&quot;a-06&quot;},{&quot;debugRoomName&quot;:&quot;a-07&quot;},{&quot;debugRoomName&quot;:&quot;a-08&quot;},{&quot;debugRoomName&quot;:&quot;a-09&quot;}]},{&quot;name&quot;:&quot;Shrine&quot;,&quot;abbreviation&quot;:&quot;SH&quot;,&quot;roomCount [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celeste_4_GoldenRidge_Normal {
            get {
                return ResourceManager.GetString("Celeste_4_GoldenRidge_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Mirror Temple&quot;,&quot;chapterSID&quot;:&quot;Celeste/5-MirrorTemple&quot;,&quot;sideName&quot;:&quot;B-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:4,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;start&quot;},{&quot;debugRoomName&quot;:&quot;a-00&quot;},{&quot;debugRoomName&quot;:&quot;a-01&quot;},{&quot;debugRoomName&quot;:&quot;a-02&quot;}]},{&quot;name&quot;:&quot;Central Chamber&quot;,&quot;abbreviation&quot;:&quot;CC&quot;,&quot;roomCount&quot;:8,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;b-00&quot;},{&quot;debugRoomName&quot;:&quot;b-01&quot;},{&quot;debugRoomName&quot;:&quot;b-04&quot;},{&quot;debugRoomName&quot;:&quot;b-02&quot;},{&quot;debugRoomName&quot;:&quot;b-06&quot;},{&quot;debugRoomName&quot;:&quot;b-07&quot;},{&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celeste_5_MirrorTemple_BSide {
            get {
                return ResourceManager.GetString("Celeste_5_MirrorTemple_BSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Mirror Temple&quot;,&quot;chapterSID&quot;:&quot;Celeste/5-MirrorTemple&quot;,&quot;sideName&quot;:&quot;C-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:3,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;00&quot;},{&quot;debugRoomName&quot;:&quot;01&quot;},{&quot;debugRoomName&quot;:&quot;02&quot;}]}],&quot;roomCount&quot;:3}.
        /// </summary>
        internal static string Celeste_5_MirrorTemple_CSide {
            get {
                return ResourceManager.GetString("Celeste_5_MirrorTemple_CSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Mirror Temple&quot;,&quot;chapterSID&quot;:&quot;Celeste/5-MirrorTemple&quot;,&quot;sideName&quot;:&quot;A-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:8,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;a-00b&quot;},{&quot;debugRoomName&quot;:&quot;a-00d&quot;},{&quot;debugRoomName&quot;:&quot;a-00c&quot;},{&quot;debugRoomName&quot;:&quot;a-00&quot;},{&quot;debugRoomName&quot;:&quot;a-01&quot;},{&quot;debugRoomName&quot;:&quot;a-08&quot;},{&quot;debugRoomName&quot;:&quot;a-12&quot;},{&quot;debugRoomName&quot;:&quot;a-13&quot;}]},{&quot;name&quot;:&quot;Depths&quot;,&quot;abbreviation&quot;:&quot;DP&quot;,&quot;roomCount&quot;:7,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;b-00&quot;},{&quot;debugRoomName&quot;:&quot;b-01&quot;},{&quot;debugRo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celeste_5_MirrorTemple_Normal {
            get {
                return ResourceManager.GetString("Celeste_5_MirrorTemple_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Reflection&quot;,&quot;chapterSID&quot;:&quot;Celeste/6-Reflection&quot;,&quot;sideName&quot;:&quot;B-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:7,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;a-00&quot;},{&quot;debugRoomName&quot;:&quot;a-01&quot;},{&quot;debugRoomName&quot;:&quot;a-02&quot;},{&quot;debugRoomName&quot;:&quot;a-03&quot;},{&quot;debugRoomName&quot;:&quot;a-04&quot;},{&quot;debugRoomName&quot;:&quot;a-05&quot;},{&quot;debugRoomName&quot;:&quot;a-06&quot;}]},{&quot;name&quot;:&quot;Reflection&quot;,&quot;abbreviation&quot;:&quot;RF&quot;,&quot;roomCount&quot;:10,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;b-00&quot;},{&quot;debugRoomName&quot;:&quot;b-01&quot;},{&quot;debugRoomName&quot;:&quot;b-02&quot;},{&quot;debugRoomN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celeste_6_Reflection_BSide {
            get {
                return ResourceManager.GetString("Celeste_6_Reflection_BSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Reflection&quot;,&quot;chapterSID&quot;:&quot;Celeste/6-Reflection&quot;,&quot;sideName&quot;:&quot;C-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:3,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;00&quot;},{&quot;debugRoomName&quot;:&quot;01&quot;},{&quot;debugRoomName&quot;:&quot;02&quot;}]}],&quot;roomCount&quot;:3}.
        /// </summary>
        internal static string Celeste_6_Reflection_CSide {
            get {
                return ResourceManager.GetString("Celeste_6_Reflection_CSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Reflection&quot;,&quot;chapterSID&quot;:&quot;Celeste/6-Reflection&quot;,&quot;sideName&quot;:&quot;A-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Lake&quot;,&quot;abbreviation&quot;:&quot;LK&quot;,&quot;roomCount&quot;:5,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;00&quot;},{&quot;debugRoomName&quot;:&quot;01&quot;},{&quot;debugRoomName&quot;:&quot;02&quot;},{&quot;debugRoomName&quot;:&quot;03&quot;},{&quot;debugRoomName&quot;:&quot;02b&quot;}]},{&quot;name&quot;:&quot;Hollows&quot;,&quot;abbreviation&quot;:&quot;HL&quot;,&quot;roomCount&quot;:17,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;04&quot;},{&quot;debugRoomName&quot;:&quot;05&quot;},{&quot;debugRoomName&quot;:&quot;06&quot;},{&quot;debugRoomName&quot;:&quot;07&quot;},{&quot;debugRoomName&quot;:&quot;08b&quot;},{&quot;debugRoomName&quot;:&quot;09&quot;},{&quot;debugRoom [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celeste_6_Reflection_Normal {
            get {
                return ResourceManager.GetString("Celeste_6_Reflection_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;The Summit&quot;,&quot;chapterSID&quot;:&quot;Celeste/7-Summit&quot;,&quot;sideName&quot;:&quot;B-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;0 M&quot;,&quot;abbreviation&quot;:&quot;0M&quot;,&quot;roomCount&quot;:4,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;a-00&quot;},{&quot;debugRoomName&quot;:&quot;a-01&quot;},{&quot;debugRoomName&quot;:&quot;a-02&quot;},{&quot;debugRoomName&quot;:&quot;a-03&quot;}]},{&quot;name&quot;:&quot;500 M&quot;,&quot;abbreviation&quot;:&quot;500M&quot;,&quot;roomCount&quot;:4,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;b-00&quot;},{&quot;debugRoomName&quot;:&quot;b-01&quot;},{&quot;debugRoomName&quot;:&quot;b-02&quot;},{&quot;debugRoomName&quot;:&quot;b-03&quot;}]},{&quot;name&quot;:&quot;1000 M&quot;,&quot;abbreviation&quot;:&quot;1K&quot;,&quot;roomCount&quot;:4,&quot;rooms&quot;:[{&quot;debugRoo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celeste_7_Summit_BSide {
            get {
                return ResourceManager.GetString("Celeste_7_Summit_BSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;The Summit&quot;,&quot;chapterSID&quot;:&quot;Celeste/7-Summit&quot;,&quot;sideName&quot;:&quot;C-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:3,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;01&quot;},{&quot;debugRoomName&quot;:&quot;02&quot;},{&quot;debugRoomName&quot;:&quot;03&quot;}]}],&quot;roomCount&quot;:3}.
        /// </summary>
        internal static string Celeste_7_Summit_CSide {
            get {
                return ResourceManager.GetString("Celeste_7_Summit_CSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;The Summit&quot;,&quot;chapterSID&quot;:&quot;Celeste/7-Summit&quot;,&quot;sideName&quot;:&quot;A-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;0 M&quot;,&quot;abbreviation&quot;:&quot;0M&quot;,&quot;roomCount&quot;:7,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;a-00&quot;},{&quot;debugRoomName&quot;:&quot;a-01&quot;},{&quot;debugRoomName&quot;:&quot;a-02&quot;},{&quot;debugRoomName&quot;:&quot;a-03&quot;},{&quot;debugRoomName&quot;:&quot;a-04&quot;},{&quot;debugRoomName&quot;:&quot;a-05&quot;},{&quot;debugRoomName&quot;:&quot;a-06&quot;}]},{&quot;name&quot;:&quot;500 M&quot;,&quot;abbreviation&quot;:&quot;500M&quot;,&quot;roomCount&quot;:9,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;b-00&quot;},{&quot;debugRoomName&quot;:&quot;b-01&quot;},{&quot;debugRoomName&quot;:&quot;b-02&quot;},{&quot;debugRoomName&quot;:&quot;b-03 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celeste_7_Summit_Normal {
            get {
                return ResourceManager.GetString("Celeste_7_Summit_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Core&quot;,&quot;chapterSID&quot;:&quot;Celeste/9-Core&quot;,&quot;sideName&quot;:&quot;B-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Into the Core&quot;,&quot;abbreviation&quot;:&quot;ITC&quot;,&quot;roomCount&quot;:6,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;a-00&quot;},{&quot;debugRoomName&quot;:&quot;a-01&quot;},{&quot;debugRoomName&quot;:&quot;a-02&quot;},{&quot;debugRoomName&quot;:&quot;a-03&quot;},{&quot;debugRoomName&quot;:&quot;a-04&quot;},{&quot;debugRoomName&quot;:&quot;a-05&quot;}]},{&quot;name&quot;:&quot;Burning or Freezing&quot;,&quot;abbreviation&quot;:&quot;BOF&quot;,&quot;roomCount&quot;:6,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;b-00&quot;},{&quot;debugRoomName&quot;:&quot;b-01&quot;},{&quot;debugRoomName&quot;:&quot;b-02&quot;},{&quot;debugRoomName&quot;:&quot;b-03&quot;},{&quot;debu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celeste_9_Core_BSide {
            get {
                return ResourceManager.GetString("Celeste_9_Core_BSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Core&quot;,&quot;chapterSID&quot;:&quot;Celeste/9-Core&quot;,&quot;sideName&quot;:&quot;C-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Start&quot;,&quot;abbreviation&quot;:&quot;ST&quot;,&quot;roomCount&quot;:3,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;00&quot;},{&quot;debugRoomName&quot;:&quot;01&quot;},{&quot;debugRoomName&quot;:&quot;02&quot;}]}],&quot;roomCount&quot;:3}.
        /// </summary>
        internal static string Celeste_9_Core_CSide {
            get {
                return ResourceManager.GetString("Celeste_9_Core_CSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Core&quot;,&quot;chapterSID&quot;:&quot;Celeste/9-Core&quot;,&quot;sideName&quot;:&quot;A-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Into the Core&quot;,&quot;abbreviation&quot;:&quot;ITC&quot;,&quot;roomCount&quot;:7,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;a-00&quot;},{&quot;debugRoomName&quot;:&quot;a-01&quot;},{&quot;debugRoomName&quot;:&quot;a-02&quot;},{&quot;debugRoomName&quot;:&quot;a-03&quot;},{&quot;debugRoomName&quot;:&quot;b-00&quot;},{&quot;debugRoomName&quot;:&quot;b-07b&quot;},{&quot;debugRoomName&quot;:&quot;b-07&quot;}]},{&quot;name&quot;:&quot;Hot and Cold&quot;,&quot;abbreviation&quot;:&quot;HAC&quot;,&quot;roomCount&quot;:5,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;c-00&quot;},{&quot;debugRoomName&quot;:&quot;c-01&quot;},{&quot;debugRoomName&quot;:&quot;c-02&quot;},{&quot;debugRoomN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celeste_9_Core_Normal {
            get {
                return ResourceManager.GetString("Celeste_9_Core_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;campaignName&quot;:&quot;Celeste&quot;,&quot;chapterName&quot;:&quot;Farewell&quot;,&quot;chapterSID&quot;:&quot;Celeste/LostLevels&quot;,&quot;sideName&quot;:&quot;A-Side&quot;,&quot;checkpoints&quot;:[{&quot;name&quot;:&quot;Singular&quot;,&quot;abbreviation&quot;:&quot;SG&quot;,&quot;roomCount&quot;:14,&quot;rooms&quot;:[{&quot;debugRoomName&quot;:&quot;a-00&quot;},{&quot;debugRoomName&quot;:&quot;a-01&quot;},{&quot;debugRoomName&quot;:&quot;a-02&quot;},{&quot;debugRoomName&quot;:&quot;a-03&quot;},{&quot;debugRoomName&quot;:&quot;a-04&quot;},{&quot;debugRoomName&quot;:&quot;a-05&quot;},{&quot;debugRoomName&quot;:&quot;b-00&quot;},{&quot;debugRoomName&quot;:&quot;b-01&quot;},{&quot;debugRoomName&quot;:&quot;b-02&quot;},{&quot;debugRoomName&quot;:&quot;b-03&quot;},{&quot;debugRoomName&quot;:&quot;b-04&quot;},{&quot;debugRoomName&quot;:&quot;b-05&quot;},{&quot;debugRoomName&quot;:&quot;b-06&quot;},{&quot;de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celeste_LostLevels_Normal {
            get {
                return ResourceManager.GetString("Celeste_LostLevels_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap goldberry_GIF {
            get {
                object obj = ResourceManager.GetObject("goldberry_GIF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
